![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [38]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

import sys

1.24.3


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [6]:
# your code goes here
null_var = np.zeros(10)
print(null_var)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [5]:
# your code goes here
var1 = np.arange(10, 50)

print(var1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [7]:
# your code goes here
matrix_1 = np.ones((2, 2), dtype=int)

print(matrix_1)

[[1 1]
 [1 1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [8]:
# your code goes here
matrix_2 = np.ones((3, 2), dtype=float)

print(matrix_2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [10]:
# your code goes here
X = np.array([[4, 6, 3], [1, 5, 2]])

twin = np.ones_like(X)

print(twin)

[[1 1 1]
 [1 1 1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [12]:
# your code goes here
X = np.array([[4, 6, 3], [1, 5, 2]])

twin2 = np.zeros_like(X)

print(twin2)

[[0 0 0]
 [0 0 0]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [72]:
# your code goes here
matrix_5 = 5 * np.ones((4, 4), dtype=int)

print(matrix_5)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [13]:
# your code goes here
X = np.array([[4, 6, 3], [1, 5, 2], [7, 8, 9]])

var2 = 7 * np.ones_like(X)

print(var2)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [15]:
# your code goes here
var3 = np.identity(3)
print(var3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [18]:
# your code goes here
var4 = np.random.randint(1, 10, size=10)

print(var4)

[9 4 6 4 2 4 4 8 2 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [25]:
# your code goes here
var5 = np.random.rand(3, 3, 3)
print(var5)

[[[0.38489021 0.3716761  0.1577688 ]
  [0.48804945 0.7371057  0.65536841]
  [0.60490046 0.56385285 0.02922115]]

 [[0.712909   0.64331765 0.9464662 ]
  [0.14929249 0.60102204 0.56781251]
  [0.03017004 0.17604857 0.1682934 ]]

 [[0.85385464 0.6796213  0.01479605]
  [0.36553853 0.28993709 0.8206553 ]
  [0.05990542 0.12950037 0.72422294]]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [26]:
# your code goes here
X = [1, 2, 3, 4, 5, 6, 7, 8, 9]

Y = np.array(X)

print(Y)

[1 2 3 4 5 6 7 8 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [27]:
# your code goes here
X = [1, 2, 3, 4, 5, 6, 7, 8, 9]

Y = np.copy(X)

print(Y)

[1 2 3 4 5 6 7 8 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [28]:
# your code goes here
var6 = np.arange(1, 11)

print(var6)

[ 1  2  3  4  5  6  7  8  9 10]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [31]:
# your code goes here
odd_nums = np.arange(1, 11, step=2)

print(odd_nums)

[1 3 5 7 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [32]:
# your code goes here
var7= np.arange(10, 0, -1)
print(var7)

[10  9  8  7  6  5  4  3  2  1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [33]:
# your code goes here
var8 = np.arange(9).reshape(3, 3)
print(var8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [43]:
# your code goes here
Z = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

memory_size = sys.getsizeof(Z)

print(f"Memory size of the matrix: {memory_size} bytes")

Memory size of the matrix: 164 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [45]:
# your code goes here
X = np.array([1, 2, 3, 4, 5])

item1 = X[0]
print(item1)

1


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [46]:
# your code goes here
X = np.array([1, 2, 3, 4, 5])

item2 = X[-1]
print(item2)

5


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [52]:
# your code goes here
X = np.array([1, 2, 3, 4, 5])

item3 = X[0:3]
print(item3)

[1 2 3]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [58]:
# your code goes here
X = np.array([1, 2, 3, 4, 5, 6, 7])

mid = X[len(X) // 2]

print("Middle number is ", mid)

Middle number is  4


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [59]:
# your code goes here
X = np.array([1, 2, 3, 4, 5, 6, 7])

reverse = X[::-1]

print(reverse)

[7 6 5 4 3 2 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [60]:
# your code goes here
X = np.array([1, 2, 3, 4, 5, 6, 7])

odd_item = X[::2]

print(odd_item)

[1 3 5 7]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [62]:
# your code goes here
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
row1 = X[0, :]

print("First row elements:", row1)

First row elements: [0 1 2]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [68]:
# your code goes here
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
row2 = X[2, :]

print("last row elements:", row2)

last row elements: [6 7 8]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [70]:
# your code goes here
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
row3 = X[0, 0]

print("first item in the first row:", row3)

first item in the first row: 0


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [71]:
# your code goes here
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
row4 = X[-1, -1]

print("last item in the last row:", row4)

last item in the last row: 8


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [75]:
# your code goes here
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
row5 = X[len(X)//2, :]

print("Middle row elements:", row5)

Middle row elements: [3 4 5]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [76]:
# your code goes here
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
var4 = X[:2, :2]

print("first two elements on the first two rows:", var4)

first two elements on the first two rows: [[0 1]
 [3 4]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [79]:
# your code goes here
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
var5 = X[-2:, -2:]

print("last two elements on the last two rows:", var5)

last two elements on the last two rows: [[4 5]
 [7 8]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [80]:
# your code goes here
array1 = np.array([8, 3, 6, 7, 1])
arr2 = array1.astype(np.float32)

print(arr2)

[8. 3. 6. 7. 1.]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [96]:
# your code goes here
arr2 = np.array([8, 3, 6, 7, 1])
var4 = arr2[::-1]
print(var4)

[1 7 6 3 8]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [97]:
# your code goes here
arr2 = [8, 3, 6, 7, 1]
sorted_arr = np.sort(arr2)

print(sorted_arr)

[1 3 6 7 8]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [94]:
# your code goes here
arr2 = np.array([8, 3, 6, 7, 2])
arr2[4] = 1
print(arr2)

[8 3 6 7 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [93]:
# your code goes here
arr2 = np.array([10, 30, 60, 50, 20])
arr2[arr2 == 50] = 40
print(arr2)

[10 30 60 40 20]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [99]:
# your code goes here
X = np.array([[8, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

X[-1, :] = 1

print(X)

[[8 2 3]
 [4 5 6]
 [1 1 1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [101]:
# your code goes here
X = np.array([[8, 2, 3],
              [4, 5, 6],
              [7, 5, 9]])

X[-1, -1] = 0

print(X)

[[8 2 3]
 [4 5 6]
 [7 5 0]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [102]:
# your code goes here
X = np.array([[8, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Y = 5 + X

print(Y)

[[13  7  8]
 [ 9 10 11]
 [12 13 14]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [103]:
# your code goes here
X = np.array([1, -2, 3, -4, 5])

Y = (X < 0)

print(Y)

[False  True False  True False]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [104]:
# your code goes here
neg_element = X[Y]
print(neg_element)

[-2 -4]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [105]:
# your code goes here
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Y = (X > 5)
above5 = X[Y]

print(above5)

[6 7 8 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [114]:
# your code goes here
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

avg_value = np.mean(X)

avg = (X > avg_value)

above_avg = X[avg]

print("The mean value is", avg_value)
print(above_avg)

The mean value is 5.0
[6 7 8 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [116]:
# your code goes here
X = np.array([1, 2, 10, 4, 2, 6, 7, 8, 9])
var2 = np.logical_or(X == 2, X == 10)

# Use the mask to extract elements equal to 2 or 10
var4 = X[var2]

print(var4)

[ 2 10  2]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [117]:
# your code goes here
X = np.array([1, 2, 10, 4, 2, 6, 7, 8, 9])
result = np.all(X != 0)

print(result)

True


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [122]:
# your code goes here
X = np.array([0, 2, 10, 4, 0, 6, 7, 8, 9])
result = np.any(X == 0)

print(result)

True


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [123]:
# your code goes here
X = np.array([0, 2, 10, 4, 0, 6, 7, 8, 9])
result = np.sum(X)

print(result)

46


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [124]:
# your code goes here
X = np.array([0, 2, 10, 4, 0, 6, 7, 8, 9])
result = np.mean(X)

print(result)

5.111111111111111


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [125]:
# your code goes here
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
result = np.sum(X, axis=0)

print(result)

[ 9 12 15]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [126]:
# your code goes here
X = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
result = np.sum(X, axis=1)

print(result)

[ 3 12 21]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [127]:
# your code goes here
X = np.array([0, 2, 10, 4, 0, 6, 7, 8, 9])
result = np.max(X)

print(result)

10


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)